---
- hosts: web
  vars:
    container_image: pbeniwal/calculator:v1
    container_name: calculator8888
  become: true
  tasks:
    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: ensure docker registry is available
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu focal stable' state=present
    - name: ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes
    - name: ensure pip is installed
      apt: name=python3-pip 
    - service: name=docker state=restarted
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull
    - name: Create container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        state: started
        published_ports: 8888:8080
